### ISSUE TITLE
Swagger documentation

### ISSUE THREAD

**Issue by TimWelter** [ujjwalguptaofficial/fortjs-swagger#2]
I feel like the swagger documentation isn't very detailed.
For example it doesn't actually show you how you need to write the swagger classes.

I have this right now and it just throws an error:
```TypeScript import { SwaggerModel, IgnoreProperty, OptionalProperty  } from "fortjs-swagger";

class Component implements SwaggerModel {
    @OptionalProperty
    name: string;
    completed: boolean;
    manNr: string;
    comment: string;
    specialAttribute: string;
    specialAttrValue: string;
    instructionImg: string;

    @IgnoreProperty
    init?(component: any) {
        this.name = component.name;
        this.completed = component.completed;
        this.manNr = component.manNr;
        this.comment = component.comment;
        this.specialAttribute = component.specialAttribute;
        this.specialAttrValue = component.specialAttrValue;
        this.instructionImg = component.instructionImg;
    }

    getExample?() {
        this.name = "component_name"
        this.completed = false
        this.manNr = "1234"
        this.comment = "comment"
        this.specialAttribute = "NONE"
        this.specialAttrValue = "value"
        this.instructionImg = "img.png"

    }
}

class Step implements SwaggerModel {
    @OptionalProperty
    _id: string
    name: string
    index: number
    completed: boolean
    components: Component[]

    @IgnoreProperty
    init?(step: any) {
        this.name = step.name;
        this.index = step.index;
        this.completed = step.completed;
        this.components = step.components
    }

    getExample?() {
        this.name = "step_name"
        this.index = 1
        this.completed = false
        this.components = [new Component()]
    }
}

export class Order implements SwaggerModel {
    @OptionalProperty
    _id: string
    serialNumber: string
    productionOrder: string
    articleNumber: string
    model: string
    assemblySteps: Step[]
    testingSteps: Step[]
    packingSteps: Step[]
    startDate: number
    endDate: number
    complete: boolean
    timer: number
    paused: boolean
    started: boolean

    @IgnoreProperty
    init?(order: any) {
        this._id = order._id
        this.serialNumber = order.serialNumber
        this.productionOrder = order.productionOrder
        this.articleNumber = order.articleNumber
        this.model = order.model
        this.assemblySteps = order.assemblySteps
        this.testingSteps = order.testingSteps
        this.packingSteps = order.packingSteps
        this.startDate = order.startDate
        this.endDate = order.endDate
        this.complete = order.complete
        this.timer = order.timer
        this.paused = order.paused
        this.started = order.started
    }

    getExample?() {
        this._id = "123456789"
        this.serialNumber = "123456789"
        this.productionOrder = "123456789"
        this.serialNumber = "123456789"
        this.model = "model_name"
        this.assemblySteps = [new Step()]
        this.testingSteps = [new Step()]
        this.packingSteps = [new Step()]
        this.startDate = Date.now()
        this.endDate = Date.now()
        this.timer = 0
        this.complete = false
        this.paused = false
        this.started = false
    }
}

**Comment by ujjwalguptaofficial** [comment]
yes, will update. 

Btw - could you tell me what's the issue ? I mean the error message you are getting.

**Comment by TimWelter** [comment]
```
(node:11436) UnhandledPromiseRejectionWarning: TypeError: Cannot convert u
    at Function.keys (<anonymous>)
    at C:\Users\weltert\Desktop\pba-api\node_modules\fortjs-swagger\build\
    at Array.forEach (<anonymous>)
    at SwaggerFormatter.module.exports../src/helpers/swagger_formatter.ts.ild\fortjs-swagger.js:976:89)
    at SwaggerFormatter.module.exports../src/helpers/swagger_formatter.ts.fortjs-swagger.js:897:31)
    at Swagger.<anonymous> (C:\Users\weltert\Desktop\pba-api\node_modules\
    at step (C:\Users\weltert\Desktop\pba-api\node_modules\fortjs-swagger\
    at Object.next (C:\Users\weltert\Desktop\pba-api\node_modules\fortjs-s
    at C:\Users\weltert\Desktop\pba-api\node_modules\fortjs-swagger\build\
    at new Promise (<anonymous>)
    at module.exports../src/models/swagger.ts.__awaiter (C:\Users\weltert\
    at Swagger.module.exports../src/models/swagger.ts.Swagger.create (C:\U
    at App../app.ts.App.initSwagger (C:\Users\weltert\Desktop\pba-api\bin\
(node:11436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will 
terminate the Node.js process with a non-zero exit code.
````

**Comment by ujjwalguptaofficial** [comment]
seems like you have defined models but not using anywhere (haven't defined the schema in controller).

please confirm.

**Comment by TimWelter** [comment]
Definitely using it.
```
@Summary("Gets all orders")
@Description("Gets all booked orders.")
@Response(HTTP_STATUS_CODE.Ok, Order) <---- Here
@Worker([HTTP_METHOD.Get])
@Route("/")
async getAllOrders() {
    return this.getOrderService.getAllOrders()
        .then((orders) => {
            return jsonResult(orders, HTTP_STATUS_CODE.Ok);
        })
        .catch((err) => {
            return jsonResult(err.message, HTTP_STATUS_CODE.InternalServerError);
        });
}
```

**Comment by ujjwalguptaofficial** [comment]
ok then it looks good to me what you have done so far. I will create the dedicated doc asap.

If you can provide me something reproducible, that would be great. Feel free to send a PR in fort-issue repo.

**Comment by TimWelter** [comment]
Added a pull request.

**Comment by ujjwalguptaofficial** [comment]
This is happening due to the nested model. 

```
friends : Friend[]
```

I have fixed it for now but not taking the friend property. Check this out in new version - 1.0.5.

I am working on seperate issue for nested property - https://github.com/ujjwalguptaofficial/fortjs-swagger/issues/5

**Comment by TimWelter** [comment]
Sorry, what exactly did is fixed in 1.0.5? I still get the error.

**Comment by ujjwalguptaofficial** [comment]
ohk, seems like need to fix the nested modeling thing. Let's talk more on that issue page. Please add yourself on that issue page by commenting something.

**Comment by ujjwalguptaofficial** [comment]
I have added some more docs. Check out the link - http://fortjs.info/tutorial/swagger/ .

Let me know if i should add about something else.

Thanks
